UnsitosDev/UnsiSmile_front

- src/app/components/private/students/components/students-general-history/history-facial-exam/history-facial-exam.component.html
- src/app/components/private/students/components/students-general-history/history-facial-exam/history-facial-exam.component.ts
- src/app/components/private/students/components/students-general-history/history-vital-signs/history-vital-signs.component.html
- src/app/components/private/students/components/students-general-history/history-vital-signs/history-vital-signs.component.ts
- src/app/core/auth.interceptor.ts
- src/app/utils/uris.contants.ts
- src/main.ts
Petición post en examen facial
> Us 38 jsons to make the requests

- package-lock.json
- src/app/components/private/students/components/form-patient-personal-data/form-patient-personal-data.component.scss
> style: cambio de color en el menu matStepLabel

- src/app/components/private/students/components/dashboard/dashboard.component.scss
- src/app/models/shared/patients/patient/patient.ts
- src/app/services/api.service.ts
- src/app/services/form-fields.service.ts
- src/app/shared/components/field-component/field-component.component.html
- src/app/shared/components/field-component/field-component.component.ts
- src/app/shared/components/tab-form/tab-form.component.html
- src/app/shared/components/tab-form/tab-form.component.ts
> Us 161 update hc

- src/app/components/private/students/components/dashboard/dashboard.component.scss
- src/app/services/form-fields.service.ts
Campo numero interior ya no es requerido
> Us 180 patient details

- src/app/services/history-clinics/general/general-history.service.ts
fix: error en getHistoryClinics
> fix: error en getHistoryClinics

- src/app/models/form-fields/form-field.interface.ts
- src/app/models/shared/patients/EthnicGroup/ethnicGroup.ts
- src/app/models/shared/patients/Religion/religion.ts
- src/app/services/form-fields.service.ts
- src/app/services/patient/patient.service.ts
- src/app/shared/components/field-component/field-component.component.html
- src/app/shared/components/field-component/field-component.component.ts
fix: solucion para enviar grupo etnico y religion para insertar paciente
> Us 210 construccion paciente

- src/app/components/private/admins/components/layout-admin/layout-admin.component.html
- src/app/components/private/admins/components/layout-admin/layout-admin.component.scss
- src/app/components/private/students/components/layout/students-layout.component.html
- src/app/components/private/students/components/layout/students-layout.component.scss
- src/app/shared/components/header/header.component.html
- src/app/shared/components/header/header.component.scss
- src/styles.scss
también se le modifico el diseño del toggleTheme
> refactor: se dejo fijo el header

- src/app/components/private/students/components/form-patient-personal-data/form-patient-personal-data.component.ts
- src/app/services/form-fields.service.ts
- src/app/services/patient/patient.service.ts
- src/app/utils/uris.contants.ts
se filtran los datos dependiendo que estado se seleciono, asi mismo con los campos municipio, localidad y colonia
> Us 175 filtrar datos domicilio

- src/app/components/private/students/components/form-patient-personal-data/form-patient-personal-data.component.ts
- src/app/services/form-fields.service.ts
- Se elimina id para crear paciente
- Segundo nombre ya no es requerido
- Se elimina campo Fecha de admision
> fix: se elimina admissionDate en formulario crear paciente

- src/app/shared/components/tab-form-update/tab-form-update.component.html
- src/app/shared/components/tab-form-update/tab-form-update.component.scss
- src/app/shared/components/tab-form-update/tab-form-update.component.ts
- src/app/shared/components/tab-form/tab-form.component.html
- src/app/shared/components/tab-form/tab-form.component.scss
- src/app/shared/components/tab-form/tab-form.component.ts
Se soluciona error al enviar archivos
> fix: se soluciona error al enviar archivos

- src/app/shared/components/tab-form-update/tab-form-update.component.html
- src/app/shared/components/tab-form-update/tab-form-update.component.ts
- src/app/shared/components/tab-form/tab-form.component.html
- src/app/shared/components/tab-form/tab-form.component.ts
Se solucionó insert en historias clinicas
> fix: se soluciono insert en historias clinicas

- src/app/shared/components/field-component/field-component.component.html
- src/app/shared/components/field-component/field-component.component.ts
Se corrige campo date en Historias clinicas
> fix: Se corrige campo date en Historias clinicas

- src/app/components/private/admins/components/admin-upload-patients/admin-upload-patients.component.html
- src/app/components/private/admins/components/admin-upload-patients/admin-upload-patients.component.scss
- src/app/components/private/admins/components/admin-upload-patients/admin-upload-patients.component.ts
- src/app/components/private/admins/components/table-admin/table-admin.component.html
- src/app/components/private/admins/components/table-admin/table-admin.component.scss
- src/app/components/private/admins/components/table-admin/table-admin.component.ts
- src/app/components/private/admins/components/table-students/table-students.component.html
- src/app/components/private/admins/components/table-students/table-students.component.scss
- src/app/components/private/admins/components/table-students/table-students.component.ts
- src/app/components/private/students/components/dashboard/dashboard.component.html
- src/app/components/private/students/components/dashboard/dashboard.component.ts
- src/app/components/private/students/components/table-patients/students-patients.component.html
- src/app/components/private/students/components/table-patients/students-patients.component.scss
- src/app/components/private/students/components/table-patients/students-patients.component.ts
- src/app/components/private/students/components/upload-patients/upload-patients.component.html
- src/app/components/private/students/components/upload-patients/upload-patients.component.scss
- src/app/components/private/students/components/upload-patients/upload-patients.component.ts
- src/app/shared/components/additional-cards/additional-cards.component.html
- src/app/shared/components/aditional-cards-student/aditional-cards-student.component.html
- src/app/shared/components/aditional-cards-student/aditional-cards-student.component.scss
- src/app/shared/components/aditional-cards-student/aditional-cards-student.component.spec.ts
- src/app/shared/components/aditional-cards-student/aditional-cards-student.component.ts
- src/app/shared/dashboard-stats-student/dashboard-stats-student.component.html
- src/app/shared/dashboard-stats-student/dashboard-stats-student.component.scss
- src/app/shared/dashboard-stats-student/dashboard-stats-student.component.spec.ts
- src/app/shared/dashboard-stats-student/dashboard-stats-student.component.ts
- src/assets/data/card-data-student.json
- src/assets/data/dashboard-stats-student.json
Se agregaron encabezados (headers) para la visualización de datos. Se implementaron datos específicos para el dashboard de administrador y estudiante
> Feat headers

- src/app/components/private/admins/components/form-patient-personal-data/form-patient-personal-data.component.ts
- src/app/components/private/students/components/card-patient-data/card-patient-data.component.html
- src/app/components/private/students/components/card-patient-data/card-patient-data.component.ts
- src/app/components/private/students/components/form-patient-personal-data/form-patient-personal-data.component.ts
- src/app/components/private/students/pages/history-clinics/dental-operation/students-dental-operation.component.ts
- src/app/components/private/students/pages/history-clinics/general/students-general-history.component.ts
- src/app/components/private/students/pages/history-clinics/oral-prosthesis/oral-prosthesis.component.ts
- src/app/components/private/students/pages/history-clinics/oral-surgery/students-oral-surgery-history.component.ts
- src/app/components/private/students/pages/history-clinics/periodontics/students-periodontics-history.component.ts
- src/app/components/private/students/pages/history-clinics/preventive-dentistry-public-health/preventive-dentistry-public-health.component.ts
- src/app/models/form-fields/form-utils.ts
- src/app/models/shared/patients/Guardian/guardian.ts
- src/app/models/shared/patients/cardPatient.ts
- src/app/models/shared/patients/patient/patient.ts
- src/app/services/form-fields.service.ts
- src/app/services/patient/patient.service.ts
- src/app/utils/uris.contants.ts
Se inserta paciente menor de edad incluyendo, estado civil de los padres
Se pinta datos adicionales en el card de tutor
> Feat insert guardian

- src/app/components/private/admins/components/admin-files-section/admin-files-section.component.html
- src/app/components/private/admins/components/admin-files-section/admin-files-section.component.scss
- src/app/components/private/admins/components/admin-files-section/admin-files-section.component.ts
- src/app/components/private/students/components/formats/formats.component.html
- src/app/components/private/students/components/formats/formats.component.scss
- src/app/components/private/students/components/formats/formats.component.ts
- src/app/components/private/students/pages/history-clinics/preventive-dentistry-public-health/preventive-dentistry-public-health.component.scss
- src/app/models/shared/formats.model.ts
- src/app/models/shared/side-nav.model.ts
- src/app/shared/components/tab-form-update/tab-form-update.component.html
- src/app/shared/components/tab-form-update/tab-form-update.component.ts
- src/app/shared/components/tab-form/tab-form.component.html
- src/app/shared/components/tab-form/tab-form.component.ts
1. Se separan botones para avanzar y guardar & avanzar y actualizar
2. Se elimina opcion para cargar paciente
3. Nueva vista para cargar archivos y obtenerlos
4. Se corrigen colores para Historia clinica Odontología preventiva y salud pública
Vista Estudiantes:
Sin archivos:
Con archivos cargados:
Vista admin:
Sin archivos:
Con archivos cargados:
> Feat buttons hc

- src/app/components/private/admins/components/form-insert-student/form-insert-student.component.ts
- src/app/services/student.service.ts
- src/app/utils/uris.contants.ts
- src/app/utils/validators.ts
se agrego el semestre y grupo a alumno
> Grupos alumno

- src/app/components/private/students/components/form-history-initial-bag/history-initial-bag.component.html
- src/app/components/private/students/components/form-history-initial-bag/history-initial-bag.component.ts
- src/app/components/private/students/pages/history-clinics/general/students-general-history.component.html
Se soluciona fix, ya no muestra boton de guardar cuando ya fue contestado el periodontograma
> Us 317 fix periodontogram

- src/app/components/private/admins/components/admin-files-section/admin-files-section.component.html
- src/app/components/private/admins/components/admin-files-section/admin-files-section.component.ts
- src/app/components/private/students/components/formats/formats.component.html
- src/app/components/private/students/components/formats/formats.component.ts
- src/app/models/shared/side-nav.model.ts
- src/app/utils/messageConfirmLeave.ts
- src/app/utils/uris.contants.ts
Fix: Se suben archivos generales
> Us 324 fix formats

- src/app/components/private/students/components/dialog-insert-profilaxis/dialog-insert-profilaxis.component.html
- src/app/components/private/students/components/dialog-insert-profilaxis/dialog-insert-profilaxis.component.ts
- src/app/components/private/students/components/fluorosis/fluorosis.component.html
- src/app/components/private/students/components/profilaxis/profilaxis.component.html
- src/assets/svg/diente_extraido.svg
- src/styles.scss
> style: colors fluorosis - profilaxis

- src/app/components/private/admins/components/dashboard-admin-stats-component/dashboard-admin-stats-component.component.html
- src/app/components/private/clinical-area-supervisor/components/review-treatment/presentation/review-treatment.component.html
- src/app/components/private/clinical-area-supervisor/components/review-treatment/presentation/review-treatment.component.scss
- src/app/components/private/clinical-area-supervisor/components/review-treatment/presentation/review-treatment.component.ts
- src/app/components/private/students/pages/patients-treatments/presentation/patients-treatment/patients-treatments.component.html
- src/app/components/private/students/pages/patients-treatments/presentation/patients-treatment/patients-treatments.component.scss
- src/app/components/private/students/pages/patients-treatments/presentation/patients-treatment/patients-treatments.component.ts
- src/app/components/private/students/pages/treatments/presentation/treatment/treatment.component.html
- src/app/components/private/students/pages/treatments/presentation/treatment/treatment.component.scss
- src/app/components/private/students/pages/treatments/presentation/treatment/treatment.component.ts
- src/styles.scss
> Us 348 refactor buttons

- src/app/components/private/admins/components/admin-files-section/admin-files-section.component.html
- src/app/components/private/admins/components/admin-files-section/admin-files-section.component.scss
- src/app/components/private/admins/components/admin-files-section/admin-files-section.component.ts
- src/app/components/private/admins/components/admin-files-section/dialog-delete-file.html
- src/app/utils/uris.contants.ts
- src/styles.scss
Se limpia el input despues de insertar
Se eliminan archivos
> Us 349 fix files

- src/app/components/private/clinical-area-supervisor/components/dialog-rate-treatment/dialog-rate-treatment.component.html
- src/app/components/private/clinical-area-supervisor/components/dialog-rate-treatment/dialog-rate-treatment.component.scss
- src/app/components/private/clinical-area-supervisor/components/dialog-rate-treatment/dialog-rate-treatment.component.ts
- src/app/components/private/students/components/dialog-confirm-send-to-review/dialog-confirm-send-to-review.component.ts
Se adapta nueva forma de enviar a revisión tratamientos y se refactoriza ui del dialog para calificar
Validaciones
Tratamiento calificado con exito
> Us 391 send review treatment
